CREATE VIEW CV_CT02_CT03 AS
WITH
  projection_2 AS (
    SELECT * FROM (
      SELECT
          SAPABAP1."/BIC/AEZO_CT032"."/BIC/EYDOCPOS" AS "_BIC_EYDOCPOS",
          SAPABAP1."/BIC/AEZO_CT032"."/BIC/EYMEMIDC" AS "_BIC_EYMEMIDC",
          SAPABAP1."/BIC/AEZO_CT032"."/BIC/EYPATIENT" AS "_BIC_EYPATIENT",
          SAPABAP1."/BIC/AEZO_CT032".EMPLGROUP AS EMPLGROUP,
          SAPABAP1."/BIC/AEZO_CT032".GENDER AS GENDER,
          SAPABAP1."/BIC/AEZO_CT032".JOB AS JOB,
          SAPABAP1."/BIC/AEZO_CT032"."/BIC/EYRULRT" AS "_BIC_EYRULRT",
          SAPABAP1."/BIC/AEZO_CT032"."/BIC/EYCTLT11" AS "_BIC_EYCTLT11",
          SAPABAP1."/BIC/AEZO_CT032"."/BIC/EYCTLT12" AS "_BIC_EYCTLT12",
          SAPABAP1."/BIC/AEZO_CT032"."/BIC/EYCTLN11" AS "_BIC_EYCTLN11",
          SAPABAP1."/BIC/AEZO_CT032"."/BIC/EYCTLN12" AS "_BIC_EYCTLN12",
          SAPABAP1."/BIC/AEZO_CT032"."/BIC/EYVSTNUM" AS "_BIC_EYVSTNUM",
          SAPABAP1."/BIC/AEZO_CT032"."/BIC/EYTRTNUM" AS "_BIC_EYTRTNUM",
          SAPABAP1."/BIC/AEZO_CT032"."/BIC/EYRULCD" AS "_BIC_EYRULCD",
          SAPABAP1."/BIC/AEZO_CT032"."/BIC/EYEVNTID" AS "_BIC_EYEVNTID",
          SAPABAP1."/BIC/AEZO_CT032".CALDAY AS CALDAY,
          SAPABAP1."/BIC/AEZO_CT032".CALMONTH AS CALMONTH,
          SAPABAP1."/BIC/AEZO_CT032".CALQUARTER AS CALQUARTER,
          SAPABAP1."/BIC/AEZO_CT032".CALYEAR AS CALYEAR,
          CASE WHEN '' != '' THEN LPAD('', 30, '0') ELSE NULL END AS CAL_PAD_TRTNUM,
          CASE WHEN '' != '' THEN LPAD('', 30, '0') ELSE NULL END AS CAL_PAD_EVENTID
      FROM SAPABAP1."/BIC/AEZO_CT032"
    ) AS calc
    WHERE (REGEXP_LIKE(calc."_BIC_EYTRTNUM", '^' || REPLACE(REPLACE(CASE WHEN '' = '' THEN '*' ELSE calc."CAL_PAD_TRTNUM" END, '*', '.*'), '?', '.') || '$')        AND
    REGEXP_LIKE(calc."_BIC_EYEVNTID", '^' || REPLACE(REPLACE(CASE WHEN '' = '' THEN '*' ELSE calc."CAL_PAD_EVENTID" END, '*', '.*'), '?', '.') || '$')           AND
    REGEXP_LIKE(calc."CALDAY", '^' || REPLACE(REPLACE(CASE WHEN '' = '' THEN '*' ELSE NULL END, '*', '.*'), '?', '.') || '$')                                    AND
    REGEXP_LIKE(calc."CALMONTH", '^' || REPLACE(REPLACE(CASE WHEN '' = '' THEN '*' ELSE NULL END, '*', '.*'), '?', '.') || '$')             AND
    REGEXP_LIKE(calc."CALQUARTER", '^' || REPLACE(REPLACE(CASE WHEN '' = '' THEN '*' ELSE NULL END, '*', '.*'), '?', '.') || '$') AND
    REGEXP_LIKE(calc."CALYEAR", '^' || REPLACE(REPLACE(CASE WHEN '' = '' THEN '*' ELSE NULL END, '*', '.*'), '?', '.') || '$'))
  ),
  projection_1 AS (
    SELECT * FROM (
      SELECT
          SAPABAP1."/BIC/AEZO_CT0200"."/BIC/EYDOCPOS" AS "_BIC_EYDOCPOS",
          SAPABAP1."/BIC/AEZO_CT0200"."/BIC/EYMEMIDC" AS "_BIC_EYMEMIDC",
          SAPABAP1."/BIC/AEZO_CT0200"."/BIC/EYPATIENT" AS "_BIC_EYPATIENT",
          SAPABAP1."/BIC/AEZO_CT0200".EMPLGROUP AS EMPLGROUP,
          SAPABAP1."/BIC/AEZO_CT0200".GENDER AS GENDER,
          SAPABAP1."/BIC/AEZO_CT0200".JOB AS JOB,
          SAPABAP1."/BIC/AEZO_CT0200"."/BIC/EYRULRT" AS "_BIC_EYRULRT",
          SAPABAP1."/BIC/AEZO_CT0200"."/BIC/EYCTLT11" AS "_BIC_EYCTLT11",
          SAPABAP1."/BIC/AEZO_CT0200"."/BIC/EYCTLT12" AS "_BIC_EYCTLT12",
          SAPABAP1."/BIC/AEZO_CT0200"."/BIC/EYCTLN11" AS "_BIC_EYCTLN11",
          SAPABAP1."/BIC/AEZO_CT0200"."/BIC/EYCTLN12" AS "_BIC_EYCTLN12",
          SAPABAP1."/BIC/AEZO_CT0200".CALDAY AS CALDAY,
          SAPABAP1."/BIC/AEZO_CT0200".CALMONTH AS CALMONTH,
          SAPABAP1."/BIC/AEZO_CT0200".CALQUARTER AS CALQUARTER,
          SAPABAP1."/BIC/AEZO_CT0200".CALYEAR AS CALYEAR,
          SAPABAP1."/BIC/AEZO_CT0200"."/BIC/EYEVNTID" AS "_BIC_EYEVNTID",
          SAPABAP1."/BIC/AEZO_CT0200"."/BIC/EYVSTNUM" AS "_BIC_EYVSTNUM",
          SAPABAP1."/BIC/AEZO_CT0200"."/BIC/EYTRTNUM" AS "_BIC_EYTRTNUM",
          SAPABAP1."/BIC/AEZO_CT0200"."/BIC/EYRULCD" AS "_BIC_EYRULCD",
          CASE WHEN '' != '' THEN LPAD('', 30, '0') ELSE NULL END AS CAL_PAD_TRTNUM,
          CASE WHEN '' != '' THEN LPAD('', 30, '0') ELSE NULL END AS CAL_PAD_EVNTID
      FROM SAPABAP1."/BIC/AEZO_CT0200"
    ) AS calc
    WHERE (REGEXP_LIKE(calc."_BIC_EYTRTNUM", '^' || REPLACE(REPLACE(CASE WHEN '' = '' THEN '*' ELSE calc."CAL_PAD_TRTNUM" END, '*', '.*'), '?', '.') || '$')        AND
    REGEXP_LIKE(calc."_BIC_EYEVNTID", '^' || REPLACE(REPLACE(CASE WHEN '' = '' THEN '*' ELSE calc."CAL_PAD_EVNTID" END, '*', '.*'), '?', '.') || '$')       AND
    REGEXP_LIKE(calc."CALDAY", '^' || REPLACE(REPLACE(CASE WHEN '' = '' THEN '*' ELSE NULL END, '*', '.*'), '?', '.') || '$')                           AND
    REGEXP_LIKE(calc."CALMONTH", '^' || REPLACE(REPLACE(CASE WHEN '' = '' THEN '*' ELSE NULL END, '*', '.*'), '?', '.') || '$')             AND
    REGEXP_LIKE(calc."CALQUARTER", '^' || REPLACE(REPLACE(CASE WHEN '' = '' THEN '*' ELSE NULL END, '*', '.*'), '?', '.') || '$') AND
    REGEXP_LIKE(calc."CALYEAR", '^' || REPLACE(REPLACE(CASE WHEN '' = '' THEN '*' ELSE NULL END, '*', '.*'), '?', '.') || '$'))
  ),
  ct02_master AS (
    SELECT
        projection_1."_BIC_EYDOCPOS" AS EYDOCPOS_CT02,
        projection_1."_BIC_EYMEMIDC" AS EYMEMIDC_CT02,
        projection_1."_BIC_EYPATIENT" AS EYPATIENT_CT02,
        projection_1.EMPLGROUP AS EMPLGROUP_CT02,
        projection_1.GENDER AS GENDER_CT02,
        projection_1.JOB AS JOB_CT02,
        projection_1."_BIC_EYRULRT" AS EYRULRT_CT02,
        projection_1."_BIC_EYCTLT11" AS EYCTLT11_CT02,
        projection_1."_BIC_EYCTLT12" AS EYCTLT12_CT02,
        projection_1."_BIC_EYCTLN11" AS EYCTLN11_CT02,
        projection_1."_BIC_EYCTLN12" AS EYCTLN12_CT02,
        projection_1.CALDAY AS CALDAY_CT02,
        projection_1.CALMONTH AS CALMONTH_CT02,
        projection_1.CALQUARTER AS CALQUARTER_CT02,
        projection_1.CALYEAR AS CALYEAR_CT02,
        projection_1."_BIC_EYEVNTID" AS EYEVNTID_CT02,
        projection_1."_BIC_EYVSTNUM" AS EYVSTNUM_CT02,
        projection_1."_BIC_EYTRTNUM" AS EYTRTNUM_CT02,
        projection_1."_BIC_EYRULCD" AS EYRULCD_CT02,
        projection_1."_BIC_EYDOCPOS" AS EYDOCPOS_CT03,
        projection_1."_BIC_EYMEMIDC" AS EYMEMIDC__CT03,
        projection_1."_BIC_EYPATIENT" AS EYPATIENT_CT03,
        projection_1.EMPLGROUP AS EMPLGROUP_CT03,
        projection_1.GENDER AS GENDER_CT03,
        projection_1.JOB AS JOB_CT03,
        projection_1."_BIC_EYRULRT" AS EYRULRT_CT03,
        projection_1."_BIC_EYCTLT11" AS EYCTLT11_CT03,
        projection_1."_BIC_EYCTLT12" AS EYCTLT12_CT03,
        projection_1."_BIC_EYCTLN11" AS EYCTLN11_CT03,
        projection_1."_BIC_EYCTLN12" AS EYCTLN12_CT03,
        projection_1."_BIC_EYVSTNUM" AS EYVSTNUM_CT03,
        projection_1."_BIC_EYTRTNUM" AS EYTRTNUM_CT03,
        projection_1."_BIC_EYRULCD" AS EYRULCD_CT03,
        projection_1."_BIC_EYEVNTID" AS EYEVNTID_CT03
    FROM projection_1
  ),
  ct03_master AS (
    SELECT
        projection_2."_BIC_EYDOCPOS" AS EYDOCPOS_CT03,
        projection_2."_BIC_EYMEMIDC" AS EYMEMIDC_CT03,
        projection_2."_BIC_EYPATIENT" AS EYPATIENT_CT03,
        projection_2.EMPLGROUP AS EMPLGROUP_CT03,
        projection_2.GENDER AS GENDER_CT03,
        projection_2.JOB AS JOB_CT03,
        projection_2."_BIC_EYRULRT" AS EYRULRT_CT03,
        projection_2."_BIC_EYCTLT11" AS EYCTLT11_CT03,
        projection_2."_BIC_EYCTLT12" AS EYCTLT12_CT03,
        projection_2."_BIC_EYCTLN11" AS EYCTLN11_CT03,
        projection_2."_BIC_EYCTLN12" AS EYCTLN12_CT03,
        projection_2."_BIC_EYVSTNUM" AS EYVSTNUM_CT03,
        projection_2."_BIC_EYTRTNUM" AS EYTRTNUM_CT03,
        projection_2."_BIC_EYRULCD" AS EYRULCD_CT03,
        projection_2."_BIC_EYEVNTID" AS EYEVNTID_CT03,
        projection_2.CALDAY AS CALDAY_CT03,
        projection_2.CALMONTH AS CALMONTH_CT03,
        projection_2.CALQUARTER AS CALQUARTER_CT03,
        projection_2.CALYEAR AS CALYEAR_CT03,
        projection_2."_BIC_EYDOCPOS" AS EYDOCPOS_CT02,
        projection_2."_BIC_EYMEMIDC" AS EYMEMIDC_CT02,
        projection_2."_BIC_EYPATIENT" AS EYPATIENT_CT02,
        projection_2.EMPLGROUP AS EMPLGROUP_CT02,
        projection_2.GENDER AS GENDER_CT02,
        projection_2.JOB AS JOB_CT02,
        projection_2."_BIC_EYRULRT" AS EYRULRT_CT02,
        projection_2."_BIC_EYCTLT11" AS EYCTLT11_CT02,
        projection_2."_BIC_EYCTLT12" AS EYCTLT12_CT02,
        projection_2."_BIC_EYCTLN11" AS EYCTLN11_CT02,
        projection_2."_BIC_EYCTLN12" AS EYCTLN12_CT02,
        projection_2.CALDAY AS CALDAY_CT02,
        projection_2.CALMONTH AS CALMONTH_CT02,
        projection_2.CALQUARTER AS CALQUARTER_CT02,
        projection_2.CALYEAR AS CALYEAR_CT02,
        projection_2."_BIC_EYEVNTID" AS EYEVNTID_CT02,
        projection_2."_BIC_EYVSTNUM" AS EYVSTNUM_CT02,
        projection_2."_BIC_EYTRTNUM" AS EYTRTNUM_CT02,
        projection_2."_BIC_EYRULCD" AS EYRULCD_CT02
    FROM projection_2
  ),
  union_1 AS (
    SELECT
        ct02_master.EYDOCPOS_CT02 AS EYDOCPOS_CT02,
        ct02_master.EYMEMIDC_CT02 AS EYMEMIDC_CT02,
        ct02_master.EYPATIENT_CT02 AS EYPATIENT_CT02,
        ct02_master.EMPLGROUP_CT02 AS EMPLGROUP_CT02,
        ct02_master.GENDER_CT02 AS GENDER_CT02,
        ct02_master.JOB_CT02 AS JOB_CT02,
        ct02_master.EYRULRT_CT02 AS EYRULRT_CT02,
        ct02_master.EYCTLT11_CT02 AS EYCTLT11_CT02,
        ct02_master.EYCTLT12_CT02 AS EYCTLT12_CT02,
        ct02_master.EYCTLN11_CT02 AS EYCTLN11_CT02,
        ct02_master.EYCTLN12_CT02 AS EYCTLN12_CT02,
        ct02_master.CALDAY_CT02 AS CALDAY_CT02,
        ct02_master.CALMONTH_CT02 AS CALMONTH_CT02,
        ct02_master.CALQUARTER_CT02 AS CALQUARTER_CT02,
        ct02_master.CALYEAR_CT02 AS CALYEAR_CT02,
        ct02_master.EYEVNTID_CT02 AS EYEVNTID_CT02,
        ct02_master.EYVSTNUM_CT02 AS EYVSTNUM_CT02,
        ct02_master.EYTRTNUM_CT02 AS EYTRTNUM_CT02,
        ct02_master.EYRULCD_CT02 AS EYRULCD_CT02,
        ct02_master.EYDOCPOS_CT03 AS EYDOCPOS_CT03,
        ct02_master.EYMEMIDC__CT03 AS EYMEMIDC__CT03,
        ct02_master.EYPATIENT_CT03 AS EYPATIENT_CT03,
        ct02_master.EMPLGROUP_CT03 AS EMPLGROUP_CT03,
        ct02_master.GENDER_CT03 AS GENDER_CT03,
        ct02_master.JOB_CT03 AS JOB_CT03,
        ct02_master.EYRULRT_CT03 AS EYRULRT_CT03,
        ct02_master.EYCTLT11_CT03 AS EYCTLT11_CT03,
        ct02_master.EYCTLT12_CT03 AS EYCTLT12_CT03,
        ct02_master.EYCTLN11_CT03 AS EYCTLN11_CT03,
        ct02_master.EYCTLN12_CT03 AS EYCTLN12_CT03,
        ct02_master.EYVSTNUM_CT03 AS EYVSTNUM_CT03,
        ct02_master.EYTRTNUM_CT03 AS EYTRTNUM_CT03,
        ct02_master.EYRULCD_CT03 AS EYRULCD_CT03,
        ct02_master.EYEVNTID_CT03 AS EYEVNTID_CT03,
        NULL AS EYMEMIDC_CT03,
        NULL AS CALDAY_CT03,
        NULL AS CALMONTH_CT03,
        NULL AS CALQUARTER_CT03,
        NULL AS CALYEAR_CT03
    FROM ct02_master
    UNION ALL
    SELECT
        ct03_master.EYDOCPOS_CT02 AS EYDOCPOS_CT02,
        ct03_master.EYMEMIDC_CT02 AS EYMEMIDC_CT02,
        ct03_master.EYPATIENT_CT02 AS EYPATIENT_CT02,
        ct03_master.EMPLGROUP_CT02 AS EMPLGROUP_CT02,
        ct03_master.GENDER_CT02 AS GENDER_CT02,
        ct03_master.JOB_CT02 AS JOB_CT02,
        ct03_master.EYRULRT_CT02 AS EYRULRT_CT02,
        ct03_master.EYCTLT11_CT02 AS EYCTLT11_CT02,
        ct03_master.EYCTLT12_CT02 AS EYCTLT12_CT02,
        ct03_master.EYCTLN11_CT02 AS EYCTLN11_CT02,
        ct03_master.EYCTLN12_CT02 AS EYCTLN12_CT02,
        ct03_master.CALDAY_CT02 AS CALDAY_CT02,
        ct03_master.CALMONTH_CT02 AS CALMONTH_CT02,
        ct03_master.CALQUARTER_CT02 AS CALQUARTER_CT02,
        ct03_master.CALYEAR_CT02 AS CALYEAR_CT02,
        ct03_master.EYEVNTID_CT02 AS EYEVNTID_CT02,
        ct03_master.EYVSTNUM_CT02 AS EYVSTNUM_CT02,
        ct03_master.EYTRTNUM_CT02 AS EYTRTNUM_CT02,
        ct03_master.EYRULCD_CT02 AS EYRULCD_CT02,
        ct03_master.EYDOCPOS_CT03 AS EYDOCPOS_CT03,
        NULL AS EYMEMIDC__CT03,
        ct03_master.EYPATIENT_CT03 AS EYPATIENT_CT03,
        ct03_master.EMPLGROUP_CT03 AS EMPLGROUP_CT03,
        ct03_master.GENDER_CT03 AS GENDER_CT03,
        ct03_master.JOB_CT03 AS JOB_CT03,
        ct03_master.EYRULRT_CT03 AS EYRULRT_CT03,
        ct03_master.EYCTLT11_CT03 AS EYCTLT11_CT03,
        ct03_master.EYCTLT12_CT03 AS EYCTLT12_CT03,
        ct03_master.EYCTLN11_CT03 AS EYCTLN11_CT03,
        ct03_master.EYCTLN12_CT03 AS EYCTLN12_CT03,
        ct03_master.EYVSTNUM_CT03 AS EYVSTNUM_CT03,
        ct03_master.EYTRTNUM_CT03 AS EYTRTNUM_CT03,
        ct03_master.EYRULCD_CT03 AS EYRULCD_CT03,
        ct03_master.EYEVNTID_CT03 AS EYEVNTID_CT03,
        ct03_master.EYMEMIDC_CT03 AS EYMEMIDC_CT03,
        ct03_master.CALDAY_CT03 AS CALDAY_CT03,
        ct03_master.CALMONTH_CT03 AS CALMONTH_CT03,
        ct03_master.CALQUARTER_CT03 AS CALQUARTER_CT03,
        ct03_master.CALYEAR_CT03 AS CALYEAR_CT03
    FROM ct03_master
  ),
  projection AS (
    SELECT
        union_1.EYVSTNUM_CT02 AS EYVSTNUM_CT02,
        union_1.EYTRTNUM_CT02 AS EYTRTNUM_CT02,
        union_1.EYRULCD_CT02 AS EYRULCD_CT02,
        union_1.EYEVNTID_CT02 AS EYEVNTID_CT02,
        union_1.CALDAY_CT02 AS CALDAY_CT02,
        union_1.CALMONTH_CT02 AS CALMONTH_CT02,
        union_1.CALQUARTER_CT02 AS CALQUARTER_CT02,
        union_1.CALYEAR_CT02 AS CALYEAR_CT02,
        union_1.EYVSTNUM_CT03 AS EYVSTNUM_CT03,
        union_1.EYTRTNUM_CT03 AS EYTRTNUM_CT03,
        union_1.EYRULCD_CT03 AS EYRULCD_CT03,
        union_1.EYEVNTID_CT03 AS EYEVNTID_CT03,
        union_1.CALDAY_CT03 AS CALDAY_CT03,
        union_1.CALMONTH_CT03 AS CALMONTH_CT03,
        union_1.CALQUARTER_CT03 AS CALQUARTER_CT03,
        union_1.CALYEAR_CT03 AS CALYEAR_CT03,
        union_1.EYDOCPOS_CT02 AS EYDOCPOS_CT02,
        union_1.EYMEMIDC_CT02 AS EYMEMIDC_CT02,
        union_1.EYPATIENT_CT02 AS EYPATIENT_CT02,
        union_1.EMPLGROUP_CT02 AS EMPLGROUP_CT02,
        union_1.GENDER_CT02 AS GENDER_CT02,
        union_1.JOB_CT02 AS JOB_CT02,
        union_1.EYRULRT_CT02 AS EYRULRT_CT02,
        union_1.EYCTLT11_CT02 AS EYCTLT11_CT02,
        union_1.EYCTLT12_CT02 AS EYCTLT12_CT02,
        union_1.EYDOCPOS_CT03 AS EYDOCPOS_CT03,
        union_1.EYMEMIDC__CT03 AS EYMEMIDC__CT03,
        union_1.EYPATIENT_CT03 AS EYPATIENT_CT03,
        union_1.EMPLGROUP_CT03 AS EMPLGROUP_CT03,
        union_1.GENDER_CT03 AS GENDER_CT03,
        union_1.JOB_CT03 AS JOB_CT03,
        union_1.EYRULRT_CT03 AS EYRULRT_CT03,
        union_1.EYCTLT11_CT03 AS EYCTLT11_CT03,
        union_1.EYCTLT12_CT03 AS EYCTLT12_CT03,
        union_1.EYMEMIDC_CT03 AS EYMEMIDC_CT03,
        union_1.EYCTLN11_CT02 AS EYCTLN11_CT02,
        union_1.EYCTLN12_CT02 AS EYCTLN12_CT02,
        union_1.EYCTLN11_CT03 AS EYCTLN11_CT03,
        union_1.EYCTLN12_CT03 AS EYCTLN12_CT03
    FROM union_1
  )

SELECT EYVSTNUM_CT02, EYTRTNUM_CT02, EYRULCD_CT02, EYEVNTID_CT02, CALDAY_CT02, CALMONTH_CT02, CALQUARTER_CT02, CALYEAR_CT02, EYVSTNUM_CT03, EYTRTNUM_CT03, EYRULCD_CT03, EYEVNTID_CT03, CALDAY_CT03, CALMONTH_CT03, CALQUARTER_CT03, CALYEAR_CT03, EYDOCPOS_CT02, EYMEMIDC_CT02, EYPATIENT_CT02, EMPLGROUP_CT02, GENDER_CT02, JOB_CT02, EYRULRT_CT02, EYCTLT11_CT02, EYCTLT12_CT02, EYCTLN11_CT02, EYCTLN12_CT02, EYDOCPOS_CT03, EYMEMIDC__CT03, EYPATIENT_CT03, EMPLGROUP_CT03, GENDER_CT03, JOB_CT03, EYRULRT_CT03, EYCTLT11_CT03, EYCTLT12_CT03, EYCTLN11_CT03, EYCTLN12_CT03, EYMEMIDC_CT03 FROM projection