CREATE VIEW CV_MCM_CNTRL_Q51 AS
WITH
  projection_2 AS (
    SELECT
        SAPABAP1.ZCACSM_DOCHD.MANDT AS MANDT,
        SAPABAP1.ZCACSM_DOCHD.POST_YEAR AS POST_YEAR,
        SAPABAP1.ZCACSM_DOCHD.BUSOBJ_TYPE AS BUSOBJ_TYPE,
        SAPABAP1.ZCACSM_DOCHD.BUSOBJ_ID AS BUSOBJ_ID,
        SAPABAP1.ZCACSM_DOCHD.DOC_ID AS DOC_ID,
        SAPABAP1.ZCACSM_DOCHD.FLG_REVERSOR AS FLG_REVERSOR,
        SAPABAP1.ZCACSM_DOCHD.FLG_REVERSED AS FLG_REVERSED,
        SAPABAP1.ZCACSM_DOCHD.DOC_TYPE AS DOC_TYPE,
        SAPABAP1.ZCACSM_DOCHD.POST_DATE AS POST_DATE
    FROM SAPABAP1.ZCACSM_DOCHD
    WHERE (("DOC_TYPE" ='1') AND ("FLG_REVERSOR" ='') AND ("FLG_REVERSED" =''))
  ),
  projection_1 AS (
    SELECT * FROM (
      SELECT
          SAPABAP1.ZCTLE_CCNTRL_ST.MANDT AS MANDT,
          SAPABAP1.ZCTLE_CCNTRL_ST.BUSOBJ_TYPE AS BUSOBJ_TYPE,
          SAPABAP1.ZCTLE_CCNTRL_ST.BUSOBJ_ID AS BUSOBJ_ID,
          SAPABAP1.ZCTLE_CCNTRL_ST.ZZTREAT_NO_BW AS ZZTREAT_NO_BW,
          SAPABAP1.ZCTLE_CCNTRL_ST.ZZTREAT_DATE AS ZZTREAT_DATE,
          SAPABAP1.ZCTLE_CCNTRL_ST.PERID AS PERID,
          SAPABAP1.ZCTLE_CCNTRL_ST.ZZPOSITION AS ZZPOSITION,
          SAPABAP1.ZCTLE_CCNTRL_ST.ZZMEMBERID AS ZZMEMBERID,
          SAPABAP1.ZCTLE_CCNTRL_ST.CONTROL_MODEL AS CONTROL_MODEL,
          SAPABAP1.ZCTLE_CCNTRL_ST.STT_CTRL AS STT_CTRL,
          SAPABAP1.ZCTLE_CCNTRL_ST.ZZTREAT_COMM_CD AS ZZTREAT_COMM_CD,
          SUBSTRING("ZZTREAT_DATE", 1, 6) AS CC_CALMONTH,
          CASE WHEN (RIGHT((SUBSTRING("ZZTREAT_DATE", 1, 6)), 2) = '01' OR RIGHT((SUBSTRING("ZZTREAT_DATE", 1, 6)), 2) = '02' OR RIGHT((SUBSTRING("ZZTREAT_DATE", 1, 6)), 2) = '03') THEN SUBSTRING("ZZTREAT_DATE", 1, 4)+'1' ELSE CASE WHEN (RIGHT((SUBSTRING("ZZTREAT_DATE", 1, 6)), 2) = '04' OR RIGHT((SUBSTRING("ZZTREAT_DATE", 1, 6)), 2) = '05' OR RIGHT((SUBSTRING("ZZTREAT_DATE", 1, 6)), 2) = '06') THEN SUBSTRING("ZZTREAT_DATE", 1, 4)+'2' ELSE CASE WHEN (RIGHT((SUBSTRING("ZZTREAT_DATE", 1, 6)), 2) = '07' OR RIGHT((SUBSTRING("ZZTREAT_DATE", 1, 6)), 2) = '08' OR RIGHT((SUBSTRING("ZZTREAT_DATE", 1, 6)), 2) = '09') THEN SUBSTRING("ZZTREAT_DATE", 1, 4)+'3' ELSE CASE WHEN (RIGHT((SUBSTRING("ZZTREAT_DATE", 1, 6)), 2) = '10' OR RIGHT((SUBSTRING("ZZTREAT_DATE", 1, 6)), 2) = '11' OR RIGHT((SUBSTRING("ZZTREAT_DATE", 1, 6)), 2) = '12') THEN SUBSTRING("ZZTREAT_DATE", 1, 4)+'4' ELSE NULL END END END END AS CC_CALQUARTER,
          SUBSTRING("ZZTREAT_DATE", 1, 4) AS CC_CALYEAR,
          RIGHT("PERID", 9) AS CC_DOCID
      FROM SAPABAP1.ZCTLE_CCNTRL_ST
    ) AS calc
    WHERE (calc."BUSOBJ_TYPE" = 'ZMR' AND calc."CONTROL_MODEL"= 'Z02' AND (calc."STT_CTRL"='AM' OR calc."STT_CTRL" = 'AA' ) AND ('''' = '' OR (DATE(calc."ZZTREAT_DATE") >= DATE('''') )) AND ('''' = '' OR (DATE(calc."ZZTREAT_DATE") <= DATE(''''))) AND (('' = 0) OR (calc."ZZTREAT_COMM_CD" = '')) AND ('''' = '' OR '''' = calc."CC_DOCID") AND ('''' = '' OR '''' = calc."ZZPOSITION") AND ('''' = '' OR '''' = calc."CC_CALMONTH") AND ('''' = '' OR '''' = calc."CC_CALQUARTER") AND ( '''' = '' OR '''' = calc."CC_CALYEAR")AND ('''' = '' OR '''' = calc."ZZMEMBERID"))
  ),
  projection_5 AS (
    SELECT
        SAPABAP1.ZCACSM_DOCINV.MANDT AS MANDT,
        SAPABAP1.ZCACSM_DOCINV.POST_YEAR AS POST_YEAR,
        SAPABAP1.ZCACSM_DOCINV.DOC_ID AS DOC_ID,
        SAPABAP1.ZCACSM_DOCINV.PART_POS AS PART_POS,
        SAPABAP1.ZCACSM_DOCINV.ZZPERSA AS ZZPERSA,
        SAPABAP1.ZCACSM_DOCINV.ZZJOBGRP AS ZZJOBGRP,
        SAPABAP1.ZCACSM_DOCINV.ZZPERNR AS ZZPERNR,
        SAPABAP1.ZCACSM_DOCINV.ZZPERSG AS ZZPERSG,
        SAPABAP1.ZCACSM_DOCINV.ZZPERSK AS ZZPERSK,
        SAPABAP1.ZCACSM_DOCINV.ZZJOB AS ZZJOB,
        SAPABAP1.ZCACSM_DOCINV.INV_POS AS INV_POS,
        SAPABAP1.ZCACSM_DOCINV.ZZOCCUPATION_COD AS ZZOCCUPATION_COD,
        SAPABAP1.ZCACSM_DOCINV.ZZFACILITY_OWNER AS ZZFACILITY_OWNER,
        SAPABAP1.ZCACSM_DOCINV.ZZFACILITY_TYPE AS ZZFACILITY_TYPE,
        SAPABAP1.ZCACSM_DOCINV.ZZFACILITY_SUBTY AS ZZFACILITY_SUBTY,
        SAPABAP1.ZCACSM_DOCINV.ZEMPCLASS AS ZEMPCLASS
    FROM SAPABAP1.ZCACSM_DOCINV
    WHERE (('''' = '' OR "ZZPERSA" = '''') AND ('''' = '' OR "ZZJOBGRP" = '''' ) AND ('''' = '' OR "ZZPERNR" = '''') AND ('''' = '' OR "ZZPERSG" = '''') AND ('''' = '' OR "ZZPERSK" = '''') AND ('''' = '' OR "ZZJOB" = '''') AND ( "ZZFACILITY_OWNER" != '01' AND "ZZFACILITY_OWNER" != '04' ) AND ( "ZZFACILITY_OWNER" != '1' AND "ZZFACILITY_OWNER" != '4' ))
  ),
  projection_3 AS (
    SELECT
        SAPABAP1.ZCACSM_DOCOBJ.MANDT AS MANDT,
        SAPABAP1.ZCACSM_DOCOBJ.POST_YEAR AS POST_YEAR,
        SAPABAP1.ZCACSM_DOCOBJ.DOC_ID AS DOC_ID,
        SAPABAP1.ZCACSM_DOCOBJ.TRI_OBJ_ID_EXT AS TRI_OBJ_ID_EXT,
        SAPABAP1.ZCACSM_DOCOBJ.TRI_OBJ_TYPE AS TRI_OBJ_TYPE,
        SAPABAP1.ZCACSM_DOCOBJ.TRI_OBJ_ID AS TRI_OBJ_ID,
        SAPABAP1.ZCACSM_DOCOBJ.FLG_REVERSED AS FLG_REVERSED,
        SAPABAP1.ZCACSM_DOCOBJ.ZZVIS_NO_BW AS ZZVIS_NO_BW,
        SAPABAP1.ZCACSM_DOCOBJ.ZZMEMBERCD AS ZZMEMBERCD
    FROM SAPABAP1.ZCACSM_DOCOBJ
    WHERE ("FLG_REVERSED" ='' AND "TRI_OBJ_TYPE" = 'Z112T'AND ('''' = '' OR '''' = "ZZMEMBERCD" ))
  ),
  projection_4 AS (
    SELECT
        SAPABAP1.ZCACSM_DOCRE.MANDT AS MANDT,
        SAPABAP1.ZCACSM_DOCRE.POST_YEAR AS POST_YEAR,
        SAPABAP1.ZCACSM_DOCRE.DOC_ID AS DOC_ID,
        SAPABAP1.ZCACSM_DOCRE.POW_OBJ_TYPE AS POW_OBJ_TYPE,
        SAPABAP1.ZCACSM_DOCRE.POW_OBJ_ID AS POW_OBJ_ID,
        SAPABAP1.ZCACSM_DOCRE.INV_POS AS INV_POS,
        SAPABAP1.ZCACSM_DOCRE.PART_POS AS PART_POS,
        SAPABAP1.ZCACSM_DOCRE.REMUNERATION AS REMUNERATION,
        SAPABAP1.ZCACSM_DOCRE.FLG_REVERSED AS FLG_REVERSED,
        SAPABAP1.ZCACSM_DOCRE.ROLE_REMUSHAR AS ROLE_REMUSHAR,
        SAPABAP1.ZCACSM_DOCRE.ZZWW004 AS ZZWW004,
        SAPABAP1.ZCACSM_DOCRE.ZZPROCESS_STAT AS ZZPROCESS_STAT,
        SAPABAP1.ZCACSM_DOCRE.UPD_TIMESTAMP AS UPD_TIMESTAMP
    FROM SAPABAP1.ZCACSM_DOCRE
    WHERE ("FLG_REVERSED" ='' AND "ROLE_REMUSHAR" =100.00000 AND ("REMUNERATION" = 'B301' OR "REMUNERATION" = 'B410') AND ("ZZPROCESS_STAT" = 'A'))
  ),
  projection_6 AS (
    SELECT
        SAPABAP1.ZCACSM_DOCPAR.MANDT AS MANDT,
        SAPABAP1.ZCACSM_DOCPAR.POST_YEAR AS POST_YEAR,
        SAPABAP1.ZCACSM_DOCPAR.DOC_ID AS DOC_ID,
        SAPABAP1.ZCACSM_DOCPAR.PART_POS AS PART_POS
    FROM SAPABAP1.ZCACSM_DOCPAR
  ),
  join_1 AS (
    SELECT
        projection_1.MANDT AS MANDT,
        projection_1.BUSOBJ_TYPE AS BUSOBJ_TYPE,
        projection_1.BUSOBJ_ID AS BUSOBJ_ID,
        projection_1.ZZTREAT_NO_BW AS ZZTREAT_NO_BW,
        projection_1.ZZTREAT_DATE AS ZZTREAT_DATE,
        projection_1.PERID AS PERID,
        projection_1.ZZPOSITION AS ZZPOSITION,
        projection_1.ZZMEMBERID AS ZZMEMBERID,
        projection_1.CONTROL_MODEL AS CONTROL_MODEL,
        projection_1.STT_CTRL AS STT_CTRL,
        projection_1.CC_CALMONTH AS CC_CALMONTH,
        projection_1.CC_CALQUARTER AS CC_CALQUARTER,
        projection_1.ZZTREAT_COMM_CD AS ZZTREAT_COMM_CD,
        projection_1.CC_DOCID AS CC_DOCID,
        projection_1.CC_CALYEAR AS CC_CALYEAR,
        projection_2.POST_YEAR AS POST_YEAR,
        projection_2.DOC_ID AS DOC_ID
    FROM projection_1
    INNER JOIN projection_2 ON projection_1.MANDT = projection_2.MANDT AND projection_1.BUSOBJ_TYPE = projection_2.BUSOBJ_TYPE AND projection_1.BUSOBJ_ID = projection_2.BUSOBJ_ID
  ),
  join_2 AS (
    SELECT
        join_1.MANDT AS MANDT,
        join_1.BUSOBJ_TYPE AS BUSOBJ_TYPE,
        join_1.BUSOBJ_ID AS BUSOBJ_ID,
        join_1.POST_YEAR AS POST_YEAR,
        join_1.DOC_ID AS DOC_ID,
        join_1.ZZTREAT_NO_BW AS ZZTREAT_NO_BW,
        join_1.ZZTREAT_DATE AS ZZTREAT_DATE,
        join_1.PERID AS PERID,
        join_1.ZZPOSITION AS ZZPOSITION,
        join_1.ZZMEMBERID AS ZZMEMBERID,
        join_1.STT_CTRL AS STT_CTRL,
        join_1.CC_CALMONTH AS CC_CALMONTH,
        join_1.CC_CALQUARTER AS CC_CALQUARTER,
        join_1.ZZTREAT_COMM_CD AS ZZTREAT_COMM_CD,
        join_1.CC_DOCID AS CC_DOCID,
        join_1.CC_CALYEAR AS CC_CALYEAR,
        projection_3.TRI_OBJ_TYPE AS TRI_OBJ_TYPE,
        projection_3.TRI_OBJ_ID AS TRI_OBJ_ID,
        projection_3.ZZVIS_NO_BW AS ZZVIS_NO_BW,
        projection_3.ZZMEMBERCD AS ZZMEMBERCD
    FROM join_1
    INNER JOIN projection_3 ON join_1.DOC_ID = projection_3.DOC_ID AND join_1.POST_YEAR = projection_3.POST_YEAR AND join_1.MANDT = projection_3.MANDT AND join_1.ZZTREAT_NO_BW = projection_3.TRI_OBJ_ID_EXT
  ),
  join_3 AS (
    SELECT
        join_2.MANDT AS MANDT,
        join_2.BUSOBJ_TYPE AS BUSOBJ_TYPE,
        join_2.BUSOBJ_ID AS BUSOBJ_ID,
        join_2.POST_YEAR AS POST_YEAR,
        join_2.DOC_ID AS DOC_ID,
        join_2.TRI_OBJ_TYPE AS TRI_OBJ_TYPE,
        join_2.ZZTREAT_NO_BW AS ZZTREAT_NO_BW,
        join_2.ZZTREAT_DATE AS ZZTREAT_DATE,
        join_2.PERID AS PERID,
        join_2.ZZPOSITION AS ZZPOSITION,
        join_2.ZZMEMBERID AS ZZMEMBERID,
        join_2.TRI_OBJ_ID AS TRI_OBJ_ID,
        join_2.STT_CTRL AS STT_CTRL,
        join_2.ZZVIS_NO_BW AS ZZVIS_NO_BW,
        join_2.CC_CALMONTH AS CC_CALMONTH,
        join_2.CC_CALQUARTER AS CC_CALQUARTER,
        join_2.ZZTREAT_COMM_CD AS ZZTREAT_COMM_CD,
        join_2.CC_DOCID AS CC_DOCID,
        join_2.CC_CALYEAR AS CC_CALYEAR,
        join_2.ZZMEMBERCD AS ZZMEMBERCD,
        projection_4.PART_POS AS PART_POS,
        projection_4.INV_POS AS INV_POS,
        projection_4.ZZWW004 AS ZZWW004,
        projection_4.UPD_TIMESTAMP AS UPD_TIMESTAMP
    FROM join_2
    INNER JOIN projection_4 ON join_2.MANDT = projection_4.MANDT AND join_2.POST_YEAR = projection_4.POST_YEAR AND join_2.DOC_ID = projection_4.DOC_ID AND join_2.TRI_OBJ_TYPE = projection_4.POW_OBJ_TYPE AND join_2.TRI_OBJ_ID = projection_4.POW_OBJ_ID
  ),
  join_4 AS (
    SELECT
        join_3.MANDT AS MANDT,
        join_3.BUSOBJ_TYPE AS BUSOBJ_TYPE,
        join_3.BUSOBJ_ID AS BUSOBJ_ID,
        join_3.POST_YEAR AS POST_YEAR,
        join_3.DOC_ID AS DOC_ID,
        join_3.TRI_OBJ_TYPE AS TRI_OBJ_TYPE,
        join_3.ZZTREAT_NO_BW AS ZZTREAT_NO_BW,
        join_3.ZZTREAT_DATE AS ZZTREAT_DATE,
        join_3.PERID AS PERID,
        join_3.ZZPOSITION AS ZZPOSITION,
        join_3.ZZMEMBERID AS ZZMEMBERID,
        join_3.STT_CTRL AS STT_CTRL,
        join_3.ZZVIS_NO_BW AS ZZVIS_NO_BW,
        join_3.CC_CALMONTH AS CC_CALMONTH,
        join_3.CC_CALQUARTER AS CC_CALQUARTER,
        join_3.ZZTREAT_COMM_CD AS ZZTREAT_COMM_CD,
        join_3.ZZWW004 AS ZZWW004,
        join_3.CC_DOCID AS CC_DOCID,
        join_3.UPD_TIMESTAMP AS UPD_TIMESTAMP,
        join_3.CC_CALYEAR AS CC_CALYEAR,
        join_3.ZZMEMBERCD AS ZZMEMBERCD,
        projection_5.PART_POS AS PART_POS,
        projection_5.ZZPERSA AS ZZPERSA,
        projection_5.ZZJOBGRP AS ZZJOBGRP,
        projection_5.ZZPERNR AS ZZPERNR,
        projection_5.ZZPERSG AS ZZPERSG,
        projection_5.ZZPERSK AS ZZPERSK,
        projection_5.ZZJOB AS ZZJOB,
        projection_5.ZZOCCUPATION_COD AS ZZOCCUPATION_COD,
        projection_5.ZZFACILITY_OWNER AS ZZFACILITY_OWNER,
        projection_5.ZZFACILITY_TYPE AS ZZFACILITY_TYPE,
        projection_5.ZZFACILITY_SUBTY AS ZZFACILITY_SUBTY,
        projection_5.ZEMPCLASS AS ZEMPCLASS
    FROM join_3
    INNER JOIN projection_5 ON join_3.MANDT = projection_5.MANDT AND join_3.POST_YEAR = projection_5.POST_YEAR AND join_3.DOC_ID = projection_5.DOC_ID AND join_3.PART_POS = projection_5.PART_POS AND join_3.INV_POS = projection_5.INV_POS
  ),
  join_5 AS (
    SELECT
        join_4.MANDT AS MANDT,
        join_4.BUSOBJ_TYPE AS BUSOBJ_TYPE,
        join_4.BUSOBJ_ID AS BUSOBJ_ID,
        join_4.POST_YEAR AS POST_YEAR,
        join_4.DOC_ID AS DOC_ID,
        join_4.TRI_OBJ_TYPE AS TRI_OBJ_TYPE,
        join_4.ZZTREAT_NO_BW AS ZZTREAT_NO_BW,
        join_4.ZZTREAT_DATE AS ZZTREAT_DATE,
        join_4.PERID AS PERID,
        join_4.ZZPOSITION AS ZZPOSITION,
        join_4.ZZMEMBERID AS ZZMEMBERID,
        join_4.ZZJOB AS ZZJOB,
        join_4.ZZPERSK AS ZZPERSK,
        join_4.ZZPERNR AS ZZPERNR,
        join_4.ZZPERSG AS ZZPERSG,
        join_4.ZZJOBGRP AS ZZJOBGRP,
        join_4.ZZPERSA AS ZZPERSA,
        join_4.STT_CTRL AS STT_CTRL,
        join_4.ZZVIS_NO_BW AS ZZVIS_NO_BW,
        join_4.CC_CALMONTH AS CC_CALMONTH,
        join_4.CC_CALQUARTER AS CC_CALQUARTER,
        join_4.ZZTREAT_COMM_CD AS ZZTREAT_COMM_CD,
        join_4.ZZOCCUPATION_COD AS ZZOCCUPATION_COD,
        join_4.ZZFACILITY_OWNER AS ZZFACILITY_OWNER,
        join_4.ZZFACILITY_TYPE AS ZZFACILITY_TYPE,
        join_4.ZZFACILITY_SUBTY AS ZZFACILITY_SUBTY,
        join_4.ZEMPCLASS AS ZEMPCLASS,
        join_4.ZZWW004 AS ZZWW004,
        join_4.CC_DOCID AS CC_DOCID,
        join_4.UPD_TIMESTAMP AS UPD_TIMESTAMP,
        join_4.CC_CALYEAR AS CC_CALYEAR,
        join_4.ZZMEMBERCD AS ZZMEMBERCD,
        projection_6.PART_POS AS PART_POS
    FROM join_4
    INNER JOIN projection_6 ON join_4.MANDT = projection_6.MANDT AND join_4.POST_YEAR = projection_6.POST_YEAR AND join_4.DOC_ID = projection_6.DOC_ID AND join_4.PART_POS = projection_6.PART_POS
  ),
  projection AS (
    SELECT
        join_5.BUSOBJ_TYPE AS BUSOBJ_TYPE,
        join_5.BUSOBJ_ID AS BUSOBJ_ID,
        join_5.POST_YEAR AS POST_YEAR,
        join_5.DOC_ID AS DOC_ID,
        join_5.TRI_OBJ_TYPE AS TRI_OBJ_TYPE,
        join_5.PART_POS AS PART_POS,
        join_5.ZZTREAT_NO_BW AS ZZTREAT_NO_BW,
        join_5.ZZTREAT_DATE AS ZZTREAT_DATE,
        join_5.PERID AS PERID,
        join_5.ZZPOSITION AS ZZPOSITION,
        join_5.ZZMEMBERID AS ZZMEMBERID,
        join_5.ZZJOB AS ZZJOB,
        join_5.ZZPERSK AS ZZPERSK,
        join_5.ZZPERNR AS ZZPERNR,
        join_5.ZZPERSG AS ZZPERSG,
        join_5.ZZJOBGRP AS ZZJOBGRP,
        join_5.ZZPERSA AS ZZPERSA,
        join_5.STT_CTRL AS STT_CTRL,
        join_5.ZZVIS_NO_BW AS ZZVIS_NO_BW,
        join_5.CC_CALMONTH AS CC_CALMONTH,
        join_5.CC_CALQUARTER AS CC_CALQUARTER,
        join_5.ZZTREAT_COMM_CD AS ZZTREAT_COMM_CD,
        join_5.ZZOCCUPATION_COD AS ZZOCCUPATION_COD,
        join_5.ZZFACILITY_OWNER AS ZZFACILITY_OWNER,
        join_5.ZZFACILITY_TYPE AS ZZFACILITY_TYPE,
        join_5.ZZFACILITY_SUBTY AS ZZFACILITY_SUBTY,
        join_5.ZEMPCLASS AS ZEMPCLASS,
        join_5.ZZWW004 AS ZZWW004,
        join_5.CC_DOCID AS CC_DOCID,
        join_5.UPD_TIMESTAMP AS UPD_TIMESTAMP,
        join_5.CC_CALYEAR AS CC_CALYEAR,
        join_5.ZZMEMBERCD AS ZZMEMBERCD
    FROM join_5
  )

SELECT BUSOBJ_TYPE, BUSOBJ_ID, POST_YEAR, DOC_ID, TRI_OBJ_TYPE, PART_POS, ZZTREAT_NO_BW, ZZTREAT_DATE, PERID, ZZPOSITION, ZZMEMBERID, ZZJOB, ZZPERSK, ZZPERNR, ZZPERSG, ZZJOBGRP, ZZPERSA, STT_CTRL, ZZVIS_NO_BW, CC_CALMONTH, CC_CALQUARTER, ZZTREAT_COMM_CD, ZZOCCUPATION_COD, ZZFACILITY_OWNER, ZZFACILITY_TYPE, ZZFACILITY_SUBTY, ZEMPCLASS, ZZWW004, CC_DOCID, UPD_TIMESTAMP, CC_CALYEAR, ZZMEMBERCD FROM projection