CREATE VIEW V_C_SOLD_MATERIALS_PROD AS
WITH
  projection_1 AS (
    SELECT
        "/KMDM/CALCULATIONVIEWS/SOLD_MATERIALS".MANDT AS MANDT,
        "/KMDM/CALCULATIONVIEWS/SOLD_MATERIALS".MATNR AS MATNR,
        "/KMDM/CALCULATIONVIEWS/SOLD_MATERIALS".ERDAT AS ERDAT
    FROM "/KMDM/CALCULATIONVIEWS/SOLD_MATERIALS"
  ),
  aggregation_2 AS (
    SELECT
        "/KMDM/CALCULATIONVIEWS/SALES_BOM".MANDT AS MANDT,
        "/KMDM/CALCULATIONVIEWS/SALES_BOM".IDNRK AS IDNRK
    FROM "/KMDM/CALCULATIONVIEWS/SALES_BOM"
    GROUP BY "/KMDM/CALCULATIONVIEWS/SALES_BOM".MANDT, "/KMDM/CALCULATIONVIEWS/SALES_BOM".IDNRK
  ),
  fert_materials AS (
    SELECT
        "/KMDM/CALCULATIONVIEWS/MATERIAL_DETAILS".MATNR AS MATNR,
        "/KMDM/CALCULATIONVIEWS/MATERIAL_DETAILS".LONG_OLD_NUMBER AS LONG_OLD_NUMBER,
        "/KMDM/CALCULATIONVIEWS/MATERIAL_DETAILS".KUNNR AS KUNNR,
        "/KMDM/CALCULATIONVIEWS/MATERIAL_DETAILS".MTART AS MTART,
        "/KMDM/CALCULATIONVIEWS/MATERIAL_DETAILS".MEINS AS MEINS,
        "/KMDM/CALCULATIONVIEWS/MATERIAL_DETAILS".MANDT AS MANDT
    FROM "/KMDM/CALCULATIONVIEWS/MATERIAL_DETAILS"
    WHERE "/KMDM/CALCULATIONVIEWS/MATERIAL_DETAILS".MTART = 'FERT'
  ),
  union_1 AS (
    SELECT
        projection_1.ERDAT AS ERDAT,
        projection_1.MANDT AS MANDT,
        projection_1.MATNR AS MATNR
    FROM projection_1
    UNION ALL
    SELECT
        NULL AS ERDAT,
        aggregation_2.MANDT AS MANDT,
        aggregation_2.IDNRK AS MATNR
    FROM aggregation_2
  ),
  join_1 AS (
    SELECT
        union_1.MANDT AS MANDT,
        union_1.ERDAT AS ERDAT,
        fert_materials.LONG_OLD_NUMBER AS LONG_OLD_NUMBER,
        fert_materials.MEINS AS MEINS
    FROM union_1
    INNER JOIN fert_materials ON union_1.MATNR = fert_materials.MATNR AND union_1.MANDT = fert_materials.MANDT
  ),
  aggregation_1 AS (
    SELECT
        join_1.LONG_OLD_NUMBER AS LONG_OLD_NUMBER,
        join_1.MEINS AS MEINS,
        join_1.MANDT AS MANDT,
        MAX(join_1.ERDAT) AS ERDAT
    FROM join_1
    GROUP BY join_1.LONG_OLD_NUMBER, join_1.MEINS, join_1.MANDT
  )

SELECT LONG_OLD_NUMBER, ERDAT, MEINS, MANDT FROM aggregation_1